apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: django-school-management-system
  labels:
    app: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: <image-name>:<tag>
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: django-volume
              mountPath: /django
      volumes:
        - name: django-volume
          emptyDir: {}
