apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: django-school-management-system
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/db-pv
