apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: django-school-management-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: db-deployment
          image: nouchka/sqlite3
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/sqlite/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pvc
