apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: django-school-management-system
  annotations:
        prometheus.io/scrape: 'true'
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
